version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-vidi_urls
      - run:
          name: Install flake8
          command: |
            mkdir -p ./env
            virtualenv ./env/vidi_urls
            source ./env/vidi_urls/bin/activate
            pip install flake8
            pip install pep8-naming
            pip install flake8-debugger
            pip install flake8-module-imports
            pip install flake8-deprecated
      - run:
          name: Run flake8
          command: |
            ./env/vidi_urls/bin/flake8 vidi_urls
      - save_cache:
          key: deps-{{ .Branch }}-vidi_urls
          paths:
            - "./env"
